### ISSUE TITLE
Unable to Import Content

### ISSUE THREAD

**Issue by drew-hansen** [llooker/looker_deployer#34]
I am trying to migrate a dashboard from one instance to another. I was able to export the Shared folder, but when I try to deploy the content to another instance I get the following error:

```
logout
ERROR: Connection Failed.
Did you specify the --no-ssl option for an ssl secured server?
You may need to use --port=443 in some cases as well.
```

I double-checked the client ID/secret as well as the port. But I am still having issues.

Thanks,
Drew

**Comment by JCPistell** [comment]
@drew-hansen Could you share a few more details? Some useful info would be:

1. What version are you running `ldeploy --version`
2. What versions of python and ruby are you using?
3. I'm assuming you have (at least) two entries in your `looker.ini` file - if you feel comfortable with it, could you share a sanitized version of that file? (get rid of the client_id and client_secret before sharing!)
4. Could you rerun the command you tried with the `--debug` flag and see if it returns any additional information?

Without any additional context I'm guessing that there's something amiss with how the SDK is trying to authenticate. Most typically this is due to the `verify_ssl` field not being set correctly or an incorrect `base_url` so you can start there.

**Comment by drew-hansen** [comment]
@JCPistell, appreciate you following up. It turns out it was a simple error. I had the port wrong. When I went to the API docs it had the port at 19999, when in reality it was 443. All good here now!

**Comment by JCPistell** [comment]
👍
